# Site settings
title: DU Minnesota
email: youn1614@umn.edu
description: Welcome to the website of the Delta Upsilon – University of Minnesota chapter!
baseurl: ""
url: "http://du-umn.com"
twitter_username: DU_UMN

# Build settings
markdown: kramdown
